###
POST http://localhost:5142/api/allergens/add-many
Content-Type: application/json

[
    {
        "Name" : "Gluten"
    },
    {
        "Name" : "Lactose"
    },
    {
        "Name" : "Nuts"
    },
    {
        "Name" : "Eggs"
    },
    {
        "Name" : "Fish"
    },
    {
        "Name" : "Meat"
    }
]

###
POST http://localhost:5142/api/allergens/add
Content-Type: application/json

{
    "Name" : "Meat"
}

### test if cascading enabled on foreign keys
DELETE http://localhost:5142/api/allergens/delete/6

###
GET http://localhost:5142/api/allergens/all

###
DELETE http://localhost:5142/api/allergens/delete-all