###
POST http://localhost:5141/api/allergens/add-many
Content-Type: application/json

[
    {
        "Name" : "Gluten",
		"MealAllergens" : []
    },
    {
        "Name" : "Lactose",
		"MealAllergens" : []
    },
    {
        "Name" : "Nuts",
		"MealAllergens" : []
    },
    {
        "Name" : "Eggs",
		"MealAllergens" : []
    },
    {
        "Name" : "Fish",
		"MealAllergens" : []
    },
    {
        "Name" : "Meat",
		"MealAllergens" : []
    }
]

###
POST http://localhost:5141/api/allergens/add
Content-Type: application/json

{
    "Name" : "Gluten",
    "MealAllergens" : []
}


###
GET http://localhost:5141/api/allergens/all

###
DELETE http://localhost:5141/api/allergens/delete/5

###
DELETE http://localhost:5141/api/allergens/delete-all