###
POST http://localhost:5141/api/meals/add
Content-Type: application/json

{
    "name" : "Caesar salad",
    "mealTime" : "Dinner",
    "type" : "Main",
    "date" : "2024-08-30",
    "allergens" : []
}

###
POST http://localhost:5141/api/meals/edit/101
Content-Type: application/json

{
    "id" : 101,
    "name" : "Caesar salatos",
    "mealTime" : "Dinner",
    "type" : "Main",
    "date" : "2024-08-30",
    "allergens" : []
}

### Test request for deleting the whole table
DELETE http://localhost:5141/api/meals/delete-all

### Test request to delete single meal
DELETE http://localhost:5141/api/meals/123

###
GET http://localhost:5141/api/meals/all

###
GET http://localhost:5141/api/meals/2024-09-02

###
GET http://localhost:5141/api/meals/meal-types
