###
POST http://localhost:5142/api/orders/add
Content-Type: application/json

{
    "participantId" : 5006,
    "mealId" : 1003,
}

###
POST http://localhost:5142/api/orders/add
Content-Type: application/json

{
    "participantId" : 5007,
    "mealId" : 1003,
}

###
POST http://localhost:5142/api/orders/add
Content-Type: application/json

{
    "participantId" : 5006,
    "mealId" : 1004,
}

###
POST http://localhost:5142/api/orders/add
Content-Type: application/json

{
    "participantId" : 5006,
    "mealId" : 1005,
}

###
GET http://localhost:5142/api/orders/all