
GET http://localhost:5168/api/participants

###

GET http://localhost:5168/weather

###
POST http://localhost:5168/api/participants
Content-Type: application/json

{
    "firstname": "Jan",
    "lastname": "Hartman",
    "age": "23"
}